<?php
$bType = array(
array('value'=>1,'text'=>'農業関係','option'=>array(
	array('value'=>1, 'text'=>'耕種農業 - 施設園芸'),
	array('value'=>2, 'text'=>'耕種農業 - 畑作・野菜'),
	array('value'=>3, 'text'=>'畜産農業 - 養豚'),
	array('value'=>4, 'text'=>'畜産農業 - 養鶏'),
	array('value'=>5, 'text'=>'畜産農業 - 酪農'),
	)),
array('value'=>2,'text'=>'漁業関係','option'=>array(
	array('value'=>1, 'text'=>'漁船漁業 - かつお一本釣り漁業'),
	array('value'=>2, 'text'=>'漁船漁業 - まぐろはえ縄漁業'),
	array('value'=>3, 'text'=>'漁船漁業 - いか釣り漁業'),
	array('value'=>4, 'text'=>'漁船漁業 - まき網漁業'),
	array('value'=>5, 'text'=>'漁船漁業 - 底曳網漁業'),
	array('value'=>6, 'text'=>'漁船漁業 - 流し網漁業'),
	array('value'=>7, 'text'=>'漁船漁業 - 定置網漁業'),
	)),
array('value'=>3,'text'=>'建設関係','option'=>array(
	array('value'=>1, 'text'=>'さく井 - パーカッション式さく井工事作業'),
	array('value'=>2, 'text'=>'さく井 - ロータリー式さく井工事作業'),
	array('value'=>3, 'text'=>'建築板金 - ダクト板金作業'),
	array('value'=>4, 'text'=>'冷凍空気調和機器施工 - 冷凍空気調和機器施工作業'),
	array('value'=>5, 'text'=>'建具製作 - 木製建具手加工作業'),
	array('value'=>6, 'text'=>'建築大工 - 大工工事作業'),
	array('value'=>7, 'text'=>'型枠施工 - 型枠工事作業'),
	array('value'=>8, 'text'=>'鉄筋施工 - 鉄筋組立て作業'),
	array('value'=>9, 'text'=>'とび - とび作業'),
	array('value'=>10,'text'=>'石材施工- 石材加工作業'),
	array('value'=>11,'text'=>'石材施工 - 石張り作業'),
	array('value'=>12,'text'=>'タイル張り - タイル張り作業'),
	array('value'=>13,'text'=>'かわらぶき - かわらぶき作業'),
	array('value'=>14,'text'=>'左官 - 左官作業'),
	array('value'=>15,'text'=>'配管 - 建築配管作業'),
	array('value'=>16,'text'=>'配管 - プラント配管作業'),
	array('value'=>17,'text'=>'熱絶縁施工 - 保温保冷工事作業'),
	array('value'=>18,'text'=>'内装仕上げ施工 - プラスチック系床仕上げ工事作業'),
	array('value'=>19,'text'=>'内装仕上げ施工 - カーペット系床仕上げ工事作業'),
	array('value'=>20,'text'=>'内装仕上げ施工 - 鋼製下地工事作業'),
	array('value'=>21,'text'=>'内装仕上げ施工 - ボード仕上げ工事作業'),
	array('value'=>22,'text'=>'内装仕上げ施工 - カーテン工事作業'),
	array('value'=>23,'text'=>'サッシ施工 - ビル用サッシ施工作業'),
	array('value'=>24,'text'=>'防水施工 - シーリング防水工事作業'),
	array('value'=>25,'text'=>'コンクリート圧送施工 - コンクリート圧送工事作業'),
	array('value'=>26,'text'=>'ウェルポイント施工 - ウェルポイント工事作業'),
	array('value'=>27,'text'=>'表装 - 壁装作業'),
	array('value'=>28,'text'=>'建設機械施工 - 押土・整地作業'),
	array('value'=>29,'text'=>'建設機械施工 - 積込み作業'),
	array('value'=>30,'text'=>'建設機械施工 - 掘削作業'),
	array('value'=>31,'text'=>'建設機械施工 - 締固め作業'),
	)),
array('value'=>4,'text'=>'食品製造関係','option'=>array(
	array('value'=>1, 'text'=>'缶詰巻締 - 缶詰巻締'),
	array('value'=>2, 'text'=>'食鳥処理加工業 - 食鳥処理加工作業'),
	array('value'=>3, 'text'=>'加熱性水産加工食品製造業 - 節類製造'),
	array('value'=>4, 'text'=>'加熱性水産加工食品製造業 - 加熱乾製品製造'),
	array('value'=>5, 'text'=>'加熱性水産加工食品製造業 - 調味加工品製造'),
	array('value'=>6, 'text'=>'加熱性水産加工食品製造業 - くん製品製造'),
	array('value'=>7, 'text'=>'非加熱性水産加工食品製造業 - 塩蔵品製造'),
	array('value'=>8, 'text'=>'非加熱性水産加工食品製造業 - 乾製品製造'),
	array('value'=>9, 'text'=>'非加熱性水産加工食品製造業 - 発酵食品製造'),
	array('value'=>10,'text'=>'水産練り製品製造 - かまぼこ製品製造作業'),
	array('value'=>11,'text'=>'ハム・ソーセージ・ベーコン製造 - ハム・ソーセージ・ベーコン製造作業'),
	array('value'=>12,'text'=>'パン製造 - パン製造作業'),
	)),
array('value'=>5,'text'=>'繊維・衣服関係','option'=>array(
	array('value'=>1, 'text'=>'紡績運転 - 前紡工程作業'),
	array('value'=>2, 'text'=>'紡績運転 - 精紡工程作業'),
	array('value'=>3, 'text'=>'紡績運転 - 巻糸工程作業'),
	array('value'=>4, 'text'=>'紡績運転 - 合撚糸工程作業'),
	array('value'=>5, 'text'=>'織布運転 - 準備工程作業'),
	array('value'=>6, 'text'=>'織布運転 - 製織工程作業'),
	array('value'=>7, 'text'=>'織布運転 - 仕上工程作業'),
	array('value'=>8, 'text'=>'染色 - 糸浸染作業'),
	array('value'=>9, 'text'=>'染色 - 織物・ニット浸染作業'),
	array('value'=>10,'text'=>'ニット製品製造 - 靴下製造作業'),
	array('value'=>11,'text'=>'ニット製品製造 - 丸編みニット製造作業'),
	array('value'=>12,'text'=>'婦人子供服製造 - 婦人子供既製服製造作業'),
	array('value'=>13,'text'=>'紳士服製造 - 紳士既製服製造作業'),
	array('value'=>14,'text'=>'寝具製作 - 寝具製作作業'),
	array('value'=>15,'text'=>'帆布製品製造 - 帆布製品製造作業'),
	array('value'=>16,'text'=>'布はく縫製 - ワイシャツ製造作業'),
	)),
array('value'=>6,'text'=>'機械・金属関係','option'=>array(
	array('value'=>1, 'text'=>'鋳造 - 鋳鉄鋳物鋳造作業'),
	array('value'=>2, 'text'=>'鋳造 - 銅合金鋳物鋳造作業'),
	array('value'=>3, 'text'=>'鋳造 - 軽合金鋳物鋳造作業'),
	array('value'=>4, 'text'=>'鍛造 - ハンマ型鍛造作業'),
	array('value'=>5, 'text'=>'鍛造 - プレス型鍛造作業'),
	array('value'=>6, 'text'=>'ダイカスト - ホットチャンバダイカスト作業'),
	array('value'=>7, 'text'=>'ダイカスト - コールドチャンバダイカスト作業'),
	array('value'=>8, 'text'=>'機械加工 - 普通旋盤作業'),
	array('value'=>9, 'text'=>'機械加工 - フライス盤作業'),
	array('value'=>10,'text'=>'金属プレス加工 - 金属プレス作業'),
	array('value'=>11,'text'=>'鉄工 - 構造物鉄工作業'),
	array('value'=>12,'text'=>'工場板金 - 機械板金作業'),
	array('value'=>13,'text'=>'めっき - 電気めっき作業'),
	array('value'=>14,'text'=>'めっき - 溶融亜鉛めっき作業'),
	array('value'=>15,'text'=>'アルミニウム陽極酸化処理 - 陽極酸化処理作業'),
	array('value'=>16,'text'=>'仕上げ - 治工具仕上げ作業'),
	array('value'=>17,'text'=>'仕上げ - 金型仕上げ作業'),
	array('value'=>18,'text'=>'仕上げ - 機械組立仕上げ作業'),
	array('value'=>19,'text'=>'機械検査 - 機械検査作業'),
	array('value'=>20,'text'=>'機械保全 - 機械系保全作業'),
	array('value'=>21,'text'=>'電子機器組立て - 電子機器組立て作業'),
	array('value'=>22,'text'=>'電気機器組立て - 回転電機組立て作業'),
	array('value'=>23,'text'=>'電気機器組立て - 変圧器組立て作業'),
	array('value'=>24,'text'=>'電気機器組立て - 配電盤・制御盤組立て作業'),
	array('value'=>25,'text'=>'電気機器組立て - 開閉制御器具組立て作業'),
	array('value'=>26,'text'=>'電気機器組立て - 回転電機巻線製作作業'),
	array('value'=>27,'text'=>'プリント配線板製造 - プリント配線板設計作業'),
	array('value'=>28,'text'=>'プリント配線板製造 - プリント配線板製造作業'),
	)),
array('value'=>7,'text'=>'その他','option'=>array(
	array('value'=>1, 'text'=>'家具製作 - 家具手加工作業'),
	array('value'=>2, 'text'=>'印刷 - オフセット印刷作業'),
	array('value'=>3, 'text'=>'製本 - 書籍製本作業'),
	array('value'=>4, 'text'=>'製本 - 雑誌製本作業'),
	array('value'=>5, 'text'=>'製本 - 商業印刷物製本作業'),
	array('value'=>6, 'text'=>'プラスチック成形 - 圧縮成形作業'),
	array('value'=>7, 'text'=>'プラスチック成形 - 射出成形作業'),
	array('value'=>8, 'text'=>'プラスチック成形 - インフレーション成形作業'),
	array('value'=>9, 'text'=>'プラスチック成形 - ブロー成形作業'),
	array('value'=>10,'text'=>'強化プラスチック成形 - 手積み積層成形作業'),
	array('value'=>11,'text'=>'塗装 - 建築塗装作業'),
	array('value'=>12,'text'=>'塗装 - 金属塗装作業'),
	array('value'=>13,'text'=>'塗装 - 鋼橋塗装作業'),
	array('value'=>14,'text'=>'塗装 - 噴霧塗装作業'),
	array('value'=>15,'text'=>'溶接 - 手溶接'),
	array('value'=>16,'text'=>'溶接 - 半自動溶接'),
	array('value'=>17,'text'=>'工業包装 - 工業包装作業'),
	)),
);

for($a=0,$aa=count($bType); $aa--; $a++){
    printf("%d : %s\n",$bType[$a]['value'],$bType[$a]['text']);
    for($b=0,$bb=count($bType[$a]['option']); $bb--; $b++){
	$option = $bType[$a]['option'];
	printf("\t%d : %s\n",$option[$b]['value'],$option[$b]['text']);
    }
}

?>
	
